// <auto-generated />
using System;
using KeitaMigration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KeitaMigration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210623221247_ComCargo")]
    partial class ComCargo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("KeitaMigration.Models.Atendimento", b =>
                {
                    b.Property<int>("AtendimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkclienteUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("FkfuncionarioUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AtendimentoId");

                    b.HasIndex("FkclienteUsuarioId");

                    b.HasIndex("FkfuncionarioUsuarioId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("KeitaMigration.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("KeitaMigration.Models.Atendimento", b =>
                {
                    b.HasOne("KeitaMigration.Models.Usuario", "Fkcliente")
                        .WithMany()
                        .HasForeignKey("FkclienteUsuarioId");

                    b.HasOne("KeitaMigration.Models.Usuario", "Fkfuncionario")
                        .WithMany()
                        .HasForeignKey("FkfuncionarioUsuarioId");

                    b.Navigation("Fkcliente");

                    b.Navigation("Fkfuncionario");
                });
#pragma warning restore 612, 618
        }
    }
}
